export const mockLastTickets = [
  {
    id: 1,
    from: 'Москва',
    fromRailway: 'Московский вокзал',
    to: 'Санкт-Петербург',
    toRailway: 'Курский вокзал',
    price: 2500,
    wifi: true,
    express: false,
    food: true,
  },
  {
    id: 2,
    from: 'Москва',
    fromRailway: 'Московский вокзал',
    to: 'Новосибирск',
    toRailway: 'Новосибирский вокзал',
    price: 1800,
    wifi: false,
    express: true,
    food: false,
  },
  {
    id: 3,
    from: 'Москва',
    fromRailway: 'Московский вокзал',
    to: 'Казань',
    toRailway: 'Казанский вокзал',
    price: 3000,
    wifi: true,
    express: false,
    food: true,
  },
]
